### ISSUE TITLE
Move all transactional emails to new html template.

### ISSUE THREAD

**Issue by cknaut** [cknaut/cinemaple#70]

**Comment by charlesrc** [comment]
views.py new_activation_link()

**Comment by charlesrc** [comment]
Add button and link in case it doesn't work.

**Comment by cknaut** [comment]
Best to use this snippet from the MC template for the button: 

`<table border="0" cellpadding="0" cellspacing="0" width="100%" class="mcnButtonBlock" style="min-width:100%;">
        <tbody class="mcnButtonBlockOuter">
            <tr>
                <td style="padding-top:0; padding-right:18px; padding-bottom:18px; padding-left:18px;" valign="top" align="center" class="mcnButtonBlockInner">
                    <table border="0" cellpadding="0" cellspacing="0" class="mcnButtonContentContainer" style="border-collapse: separate !important;border-radius: 4px;background-color: #0069D9;">
                        <tbody>
                            <tr>
                                <td align="center" valign="middle" class="mcnButtonContent" style="font-family: Arial; font-size: 16px; padding: 18px;">
                                    <a class="mcnButton " title="Buy Now" href="https://www.cinemaple.com/curr_mov_nights" target="_blank" style="font-weight: bold;letter-spacing: normal;line-height: 100%;text-align: center;text-decoration: none;color: #FFFFFF;">More Info / Register</a>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </td>
            </tr>
        </tbody>
    </table>`

**Comment by charlesrc** [comment]
Should we good now (for all emails sent from forms.py), with the right button design. I saw you did some changes in guest_invite.html so I left it as is.
