### ISSUE TITLE
No trailer available case on landing page

### ISSUE THREAD

**Issue by charlesrc** [cknaut/cinemaple#72]
Something I have noticed on my local version: if no trailer available, landing page trailer (in accordion) opens new inset window to landing page (where trailer should be). 

One possible solution would be not to include the trailer (add if statement in landing page). Doesn't really matter because most likely every winning movie will have a trailer.

**Comment by cknaut** [comment]
We should do the former (not showing a trailer). This is trivial and already implemented in the add_mov_nights and curr_mov_nights pages.
