### ISSUE TITLE
Add FAQ in logged in section explaining the process.

### ISSUE THREAD

**Issue by cknaut** [cknaut/cinemaple#79]

**Comment by charlesrc** [comment]
TODO:
-- Add FAQ section link in every page.
-- Add questions: 
"What is cinemaple?"
"How does it work?" make a drawing
"How can I invite my friends to cinemaple?"
"What if I have comments/suggestions...?"
"What about my data?"
"Why so many emojis?"

**Comment by charlesrc** [comment]
Just need to add a word on voting system @cknaut
