### ISSUE TITLE
Correct header height for small displays.

### ISSUE THREAD

**Issue by cknaut** [cknaut/cinemaple#86]
![image](https://user-images.githubusercontent.com/4958226/68078471-84756880-fdac-11e9-8005-6705508e7789.png)

**Comment by charlesrc** [comment]
min-width 768px still bugged but should be fine for now (please check works on small screens) @cknaut

**Comment by cknaut** [comment]
Looks good now, thanks.

![image](https://user-images.githubusercontent.com/4958226/68099133-e3131300-fe8e-11e9-82d0-b5b9f269102d.png)
