### ISSUE TITLE
Signup page not showing username line.

### ISSUE THREAD

**Issue by cknaut** [cknaut/cinemaple#88]
I think this issue first showed up after adding the privacy policy, we should investigate.

![image](https://user-images.githubusercontent.com/4958226/68099643-806f4680-fe91-11e9-9724-16b03ac832be.png)

**Comment by charlesrc** [comment]
This is strange, because it shows us properly on my screen for any aspect ratio. 
![image](https://user-images.githubusercontent.com/13108109/68141593-cfea5c80-fefb-11e9-996e-7799ccf71225.png)

**Comment by charlesrc** [comment]
![image](https://user-images.githubusercontent.com/13108109/68141621-dc6eb500-fefb-11e9-963a-00cdb542743c.png)

**Comment by cknaut** [comment]
I can replicate this problem on a larger screen: Initially, I can see all fields, but when I decrease the height of the window, the fields are getting subsequently clipped.

**Comment by charlesrc** [comment]
This is indeed a problem that seems to appear on screens when the max-size of the screen is "small" (some max-width < XXX) however on bigger screens I could not see it. In any case, it should be solved now... Please double-check.
